# Generated by Django 5.0.4 on 2024-04-11 00:11

import documentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_alter_documento_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to=documentos.models.user_directory_path),
        ),
    ]
